### ISSUE TITLE
.gitignore is not being copied

### ISSUE THREAD

**Issue by daffl** [feathersjs/generator-feathers-plugin#16]
It looks like `.gitignore` is not being copied when initializing a new plugin.

**Comment by ekryski** [comment]
Dammit this is not fixed. It's an issue with npm that I guess is pretty common. https://github.com/npm/npm/issues/3763

Fix incoming.

**Comment by ekryski** [comment]
Fixed in https://github.com/feathersjs/generator-feathers-plugin/releases/tag/v0.6.4
