### ISSUE TITLE
Is this generator a recommended boilerplate for feathers database adapters?

### ISSUE THREAD

**Issue by sajov** [feathersjs/generator-feathers-plugin#24]
thanks for reply

**Comment by ekryski** [comment]
Yes. It doesn't really matter where the resource comes from. Could also be an API, file system, etc.

**Comment by daffl** [comment]
To add a little to it, this generators is the base for all the Feathers plugins that we publish to npm, including if you would like to provide an adapter for another database to the community. To create your own adapter the application service generator (`feathers generate service` and then choosing that you want to write your own) would be sufficient.
