### ISSUE TITLE
No example/app created

### ISSUE THREAD

**Issue by aawaheed** [feathersjs/generator-feathers-plugin#41]
when running `yo feathers-plugin` an example folder along with app.js is expected to be created however that's not the case.
![screen shot 2017-01-18 at 2 39 39 pm](https://cloud.githubusercontent.com/assets/6452873/22062681/00f06e76-dd8c-11e6-8694-b8619f0866d1.png)

**Comment by aawaheed** [comment]
node: v7.2.1
npm: 4.0.3

**Comment by daffl** [comment]
I don't think it's supposed to create an example.

**Comment by marshallswain** [comment]
@aawaheed what made you think it should?

**Comment by aawaheed** [comment]
@marshallswain just following the [guide](https://docs.feathersjs.com/guides/creating-a-plugin.html). @daffl Probably we need to update the guide then?

**Comment by daffl** [comment]
I totally forgot we had a guide. Yes please, if you could update that (you can edit the page directly [here](https://github.com/feathersjs/feathers-docs/edit/master/guides/creating-a-plugin.md)) that would be great!

**Comment by ekryski** [comment]
Fixed it in the guide. Closing
